version: '3'

volumes:
  postgres:
  pgadmin:
  postgres_data:
    driver: local

networks:
  postgres:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./data:/data/postgres"
      - "./postgres_init:/docker-entrypoint-initdb.d/postgres_init.sql"
    environment:
      POSTGRES_DB: fcr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  server:
    container_name: server
    image: student-roadmap-backend
    build:
      context: ./fcr-backend
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=fcr
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: food-wiz_client
    build:
      context: ./fcr-frontend
      dockerfile: Dockerfile
    command: [ "npm", "start" ]
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - server
    stdin_open: true
    tty: true