apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: quarkus-claim # Sets name of PV
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 2Gi # Sets volume size
