name: Student Roadmap CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: build-and-release
  
jobs:   
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bobannikolov/student-roadmap-backend:latest
      -
        name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bobannikolov/student-roadmap-frontend:latest
    
